project:
  type: website
  output-dir: docs

website:
  title: "Weverthon Machado"
  site-url: 'https://weverthon.com'
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: CV
        file: files/cv-wm.pdf
      - text: Research
        file: research/index.qmd
  google-analytics: 
    tracking-id: "G-LTHR65D61V"
    storage: "none" 


format:
  html:
    theme: journal
    css: styles.css
    toc: true



